apiVersion: v2
name: mlflow
description: MLflow - an open source platform for the machine learning lifecycle
type: application
version: 0.1.0
appVersion: 1.17.0
maintainers:
  - name: getindata
    email: mlops@getindata.com
    url: https://getindata.com
